### ISSUE TITLE
Checkboxes don't work with Spring MVC JSTL

### ISSUE THREAD

**Issue by matthiasrohr** [flatlogic/awesome-bootstrap-checkbox#14]
Hi! First of all: Great work! Unfortunately, the checkboxes do not seem to work with Spring MVC JSTL. There seems to be a problem with the hidden input field that is inserted by the form:checkbox tag automatically after the checkbox input field. Here is an example of how the generated HTML looks like:

<code>
&lt;div class=&quot;checkbox checkbox-primary&quot;&gt;
	&lt;input id=&quot;checkbox1&quot; name=&quot;enabled&quot; type=&quot;checkbox&quot; value=&quot;true&quot;/&gt;&lt;input type=&quot;hidden&quot; name=&quot;_enabled&quot; value=&quot;on&quot;/&gt; 
         &lt;label for=&quot;checkbox1&quot;&gt;Primary&lt;/label&gt;
&lt;/div&gt;
</code>

When I remove the hidden field or move it after the label it works fine (but this is of course not really an option here). I tested this with both Chrome and Firefox.

**Comment by okendoken** [comment]
Hi @matthiasrohr 

Thanks for your appreciation!

A visible checkbox is triggered when actual input changes its state to `:checked`. This is achieved by using `+` selector in this line - https://github.com/flatlogic/awesome-bootstrap-checkbox/blob/master/awesome-bootstrap-checkbox.css#L39

    .checkbox input[type="checkbox"]:checked + label::after {
        font-family: 'FontAwesome';
        content: "\f00c"; }

In order to fix the problem we need to change `+` to `~`. As discussed in #1 we've decided to leave `+` selector because of its better compatibility.

I am not familiar with Spring MVC components but I would advice to try to find a way to override/extend the component you are using.
