### ISSUE TITLE
Does not work with asp.net mvc taghelpers

### ISSUE THREAD

**Issue by oliverhunt** [flatlogic/awesome-bootstrap-checkbox#50]
The html helpers in the razor syntax generate an additional hidden input which causes this checkbox library to not work

**Comment by IrvinDominin** [comment]
+1 I'm facing the same issue too, and was a little bit funny to find it out. Is there eventually a workaround?

**Comment by ajmudrak** [comment]
I was able to find a workaround for this in the css file by doing a find/replace of all "+ label" and changing that to "~ label".  

The way awesome-bootstrap-checkbox is currently set up, the label has to be the next sibling after the checkbox (use of the "+" css selector).  Bit if we use "~", the css general sibling selector, for the label, this problem is resolved because the label just has to be somewhere within the enclosing div.

This change requires that the label and the input tag for the checkbox be in their own div or span, so that they are the only siblings of type input and label.

(This might be a viable long-term solution, but it does change the behavior slightly.  Though I think it fits within the general guidelines of the documentation.)

**Comment by DimaSavchenko** [comment]
Guys, thanks! This problem has been solved here:
https://github.com/flatlogic/awesome-bootstrap-checkbox/issues/1
https://github.com/flatlogic/awesome-bootstrap-checkbox/issues/4

**Comment by morilon** [comment]
You can change 

```
.checkbox input[type="checkbox"]:checked + label::after,
.checkbox input[type="radio"]:checked + label::after {
```

into

```
.checkbox input[type="checkbox"]:checked + label::after,
.checkbox input[type="checkbox"]:checked + input[type="hidden"] + label::after,
.checkbox input[type="radio"]:checked + label::after,
.checkbox input[type="radio"]:checked + input[type="hidden"] + label::after {
```
